(part "5010"
    (packageRef "5010")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "220")
    (property "Mouser_Part_Number" "534-5010")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Keystone-Electronics/5010?qs=qOqV1E1P08SzD%252BWfk1wMXQ%3D%3D")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "5010")
    (property "Description" "KEYSTONE - 5010 - TEST POINT, PCB, THROUGH HOLE")
    (property "Datasheet_Link" "")
    (property "symbolName1" "5010")
)
