(part "3386G-1-472LF"
    (packageRef "3386G1503LF")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "652-3386G-1-472LF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/3386G-1-472LF?qs=jh2Y1wKDsmisnPC5JCu25Q%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "3386G-1-472LF")
    (property "Description" "Trimmer Resistors - Through Hole 3/8" 4.7Kohms 10% 0.5Watts Square")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/3386G-1-503LF.pdf")
    (property "symbolName1" "3386G-1-472LF")
)
