(part "NMA1209SC"
    (packageRef "NMA1209SC")
    (interface
        (port "1" (symbPinId 1) (portName "+VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-VIN") (portType INOUT))
        (port "4" (symbPinId 3) (portName "-VOUT") (portType INOUT))
        (port "5" (symbPinId 4) (portName "OV") (portType INOUT))
        (port "6" (symbPinId 5) (portName "+VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "580-NMA1209SC")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Power-Solutions/NMA1209SC?qs=Z7IUn5gUMVNP8y%252Bxli9kPg%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "NMA1209SC")
    (property "Description" "Isolated Module DC DC Converter 2 Output 9V -9V 55mA, 55mA 10.8V - 13.2V Input")
    (property "Datasheet_Link" "https://www.murata.com/products/productdata/8807031013406/kdc-nma.pdf")
    (property "symbolName1" "NMA1209SC")
)
