(part "1904147"
    (packageRef "1904147")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "651-1904147")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Phoenix-Contact/1904147?qs=71zq8cT40ISVFWCxilHzsw%3D%3D")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1904147")
    (property "Description" "PCB Terminal Block 1904147")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/SFDatasheet-2/sf-00056479.pdf")
    (property "symbolName1" "1904147")
)
