(part "S2A"
    (packageRef "DIOM5336X245N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "512-S2A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/S2A?qs=RJwZ8kJo1mjHOxt0JeuTsQ%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "S2A")
    (property "Description" "High-Current Capability, 2 A Rated; Fast Response: 2 us Trr; Glass Passivated Junction; High-Surge Current Capability, 50 A2s IFSM; Low-Forward Voltage Drop, 1.15 V VF Max at 2 A; UL Certified, UL #E258596; NRV Prefix for Automotive and Other Applications Requiring Unique Site and Control Change Requirements; AECQ101 Qualified and PPAP Capable; These Devices are PbFree and are RoHS Compliant")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/S2M-D.PDF")
    (property "symbolName1" "S2A")
)
