(part "11R683C"
    (packageRef "11R683C")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "580-11R683C")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Power-Solutions/11R683C?qs=gLyyx31KZaC4f%252BbxyZuUbg%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "11R683C")
    (property "Description" "Murata 68 uH +/-10% Radial Inductor, Max SRF:1kHz, 0.4A Idc, 0.85 Rdc 1100R")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/P02A/kmp_1100r.pdf")
    (property "symbolName1" "11R683C")
)
