(part "11R473C"
    (packageRef "11R473C")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "580-11R473C")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Power-Solutions/11R473C?qs=gLyyx31KZaDYIC8Ij6WybA%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "11R473C")
    (property "Description" "Fixed Inductors Ind 47uH 0.5A Radial Leads")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/P02A/kmp_1100r.pdf")
    (property "symbolName1" "11R473C")
)
