(part "1984785"
    (packageRef "1984785")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "651-1984785")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Phoenix-Contact/1984785?qs=MCbhYIqTEtldDub9XDF2qg%3D%3D")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1984785")
    (property "Description" "PCB terminal block, nominal current: 17.5 A, rated voltage (III/2): 200 V, nominal cross section: 1.5 mm?, Number of potentials: 4, Number of rows: 1, Number of positions per row: 4, product range: PT 1,5/..-V, pitch: 3.5 mm, connection method: Screw connection with wire protector, mounting: Wave soldering, conductor/PCB connection direction: 90 ?, color: green, Pin layout: Linear pinning, Solder pin [P]: 4.5 mm, type of packaging: packed in cardboard")
    (property "Datasheet_Link" "http://www.phoenixcontact.com/de/produkte/1984785/pdf")
    (property "symbolName1" "1984785")
)
