(part "1190366"
    (packageRef "1190366")
    (interface
        (port "A1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "A2" (symbPinId 2) (portName "A2") (portType INOUT))
        (port "A3" (symbPinId 3) (portName "A3") (portType INOUT))
        (port "A4" (symbPinId 4) (portName "A4") (portType INOUT))
        (port "A5" (symbPinId 5) (portName "A5") (portType INOUT))
        (port "B1" (symbPinId 6) (portName "B1") (portType INOUT))
        (port "B2" (symbPinId 7) (portName "B2") (portType INOUT))
        (port "B3" (symbPinId 8) (portName "B3") (portType INOUT))
        (port "B4" (symbPinId 9) (portName "B4") (portType INOUT))
        (port "B5" (symbPinId 10) (portName "B5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "651-1190366")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Phoenix-Contact/1190366?qs=QNEnbhJQKvbQxItN%252B93NHg%3D%3D")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1190366")
    (property "Description" "5 Position Wire to Board Terminal Block 30 (150) Angle with Board 0.197" (5.00mm) Through Hole")
    (property "Datasheet_Link" "https://www.phoenixcontact.com/online/portal/us?uri=pxc-oc-itemdetail:pid=1190366&library=usen&tab=1")
    (property "symbolName1" "1190366")
)
