(part "RA-T2X-64E"
    (packageRef "RAT2X64E")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Ohmite")
    (property "Manufacturer_Part_Number" "RA-T2X-64E")
    (property "Mouser_Part_Number" "588-RA-T2X-64E")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Ohmite/RA-T2X-64E?qs=wmFqszA%252Be7Ma8WH5xwhOHA%3D%3D")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "Heat Sink TO-218, TO-220, TO-247 Aluminum 4.0W @ 20C Board Level, Vertical")
    (property "Datasheet_Link" "https://www.ohmite.com/assets/docs/sink_f_r.pdf?r=false")
    (property "symbolName1" "RA-T2X-64E")
)
