(part "TB005-762-02BE"
    (packageRef "TB00576202BE")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "490-TB005-762-02BE")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/TB005-762-02BE?qs=vLWxofP3U2zXv1H2wuShow%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "TB005-762-02BE")
    (property "Description" "2~24 Poles, Screw Type, Horizontal, 7.62 Pitch, 26~10 (AWG), Terminal Block Connector")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/supplyframepdf/tb005-762.pdf")
    (property "symbolName1" "TB005-762-02BE")
)
